### ISSUE TITLE
[Self-hosting] aarch64 support

### ISSUE THREAD

**Issue by Kex1016** [Phineas/lanyard#244]
Running the provided docker-compose file gives an `exec format error` message on aarch64 based machines:

```yml
version: "3.8"

services:
  redis:
    image: redis
    restart: always
    container_name: lanyard_redis
  lanyard:
    image: phineas/lanyard:latest
    restart: always
    container_name: lanyard
    depends_on:
      - redis
    ports:
      - 4001:4001
    environment:
      BOT_TOKEN: <token>
      REDIS_HOST: redis
```

```
~/docker/lanyard$ sudo docker container logs <container_id>
exec /opt/lanyard/bin/lanyard: exec format error
```
